joint_limits:
  arm_1_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  arm_2_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  arm_3_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  arm_4_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  arm_5_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  arm_6_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  arm_7_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  sdh_finger_21_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  sdh_finger_22_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  sdh_finger_23_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  sdh_knuckle_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  sdh_finger_12_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  sdh_finger_13_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  sdh_thumb_2_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  sdh_thumb_3_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  torso_lower_neck_tilt_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  torso_pan_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  torso_upper_neck_tilt_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  torso_tray_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false