planner_configs:
  SBLkConfig1:
    type: kinematic::SBL
  LBKPIECEkConfig1:
    type: kinematic::LBKPIECE
groups:
  - arm
  - arm_cartesian
arm:
  planner_type: JointPlanner
  planner_configs:
    - SBLkConfig1
    - LBKPIECEkConfig1
  projection_evaluator: joint_state
arm_cartesian:
  parent_frame: base_link
  physical_group: arm
  planner_type: RPYIKTaskSpacePlanner
  state_spaces:
    - x
    - y
    - z
    - roll
    - pitch
    - yaw
  x:
    type: Linear
    min: -2.0
    max: 2.0
  y:
    type: Linear
    min: -2.0
    max: 2.0
  z:
    type: Linear
    min: -2.0
    max: 2.0
  roll:
    type: Revolute
  pitch:
    type: Revolute
  yaw:
    type: Revolute
  planner_configs:
    - SBLkConfig1
    - LBKPIECEkConfig1
  ##@ToDo: Replace 'kinematic_solver' with your plugin name and OMPL will use it when making IK calls. 
  kinematics_solver: arm_kinematics_constraint_aware/KDLArmKinematicsPlugin
  tip_name: arm_7_link
  root_name: base_link
  ## Added robot name for ik solutions - LWA with SDH extended ##
  robot: lwa_sdh_ext
  projection_evaluator: joint_state
  longest_valid_segment_fraction: 0.001
